### ISSUE TITLE
Cannot parse a JavaScript project

### ISSUE THREAD

**Issue by codeorcode** [Ericsson/CodeCompass#201]
Hi,

How can I parse a JavaScript project ?

I've tried this:

CodeCompass parse -f -w /home/john/cc/workdir -n queens  --dbuser ovi --labels "source=/home/john/cc/queens" --dbport 6250

And then I've tried to access it via:

http://10.0.1.37:6251/#wsid=queens

but I get a blank page.

I apologise for posting this here. I did not find the answer on documentation or wiki or via google.

Thank you and best regards!

**Comment by bruntib** [comment]
Hi,

It seems to me that you are using the Earhart version which is not supported any more. The documentation of the new version can be found here: https://github.com/Ericsson/CodeCompass/blob/master/doc/usage.md.

CodeCompass currently doesn't contain JavaScript parser, thus only search indexing will be done. Due to the pluginable architecture one can create new parsers under https://github.com/Ericsson/CodeCompass/tree/master/plugins. We are planning to create a basic development documentation in the future for getting started.

If you really started the server by `CodeCompass server` command then the page should open. In case of this blank page the browser console should be checked first (F12 key opens it usually). Open the console and then reload the page. The error messages should help. The `CodeCompass` sub-commands can also be run with debug verbosity (see the help commands, e.g. `CodeCompass server -h`) for useful information.

If you still have problem by launching CodeCompass, don't hesitate to contact us.

Best regards!

**Comment by bruntib** [comment]
I close this ticket for now. If there are further questions, please reopen it.
