### ISSUE TITLE
Configuration issues with setting up the environment

### ISSUE THREAD

**Issue by aogrcs** [Ericsson/CodeCompass#228]

**Comment by whisperity** [comment]
The build_deps file is for an older version of the system. Check `docs/deps.md` on how the current master version is to be deployed.

**Comment by aogrcs** [comment]
Hi, I check deps.md with the known issues for LLVM/Clang. After make install, there is an error said that could not find clang-6.0. I set DCMAKE_INSTALL_PREFIX=/usr/bin, which contain clang-3.8. And it maybe the source, how could I set the clang-6.0 path? Thanks!
Sincerely

**Comment by whisperity** [comment]
LLVM/Clang obtainable from the package manager isn't usable with CodeCompass at this point (there are upcoming fixes to this not yet fleshed out). The `deps.md` file contains the guide on how to manually compile and install Clang on your system. These manual installs most likely shouldn't go under something like `/usr` but rather a custom folder that is not overlapping with standard binary locations. The guide talks about installing Clang to some folder in your home directory.

**Comment by whisperity** [comment]
What does your `/var/log/syslog` (be careful for log rotation if a day has passed since) say about the time where the build was killed?

It sounds to me as if you don't have enough memory. And because the linker keeps eating and eating away memory to create the built binary, it simply runs out of available memory and the kernel decides to annihilate the memory hog, and this is why it kills the process.

**Comment by whisperity** [comment]
There are a few compile options that could help lessen the memory requirement of compilation:

 * `-DLLVM_TARGETS_TO_BUILD=X86` will only compile the X86-related compilers. Because we only use LLVM for code analysis (and that works for every platform despite the value specified here), there is no need to create a binary that can **compile** C++ to ARM, MIPS and various other architectures. Being able to compile to x86 is good (and as far as I know, "targets to build: none" is not an option), because you can still compile CodeCompass with Clang.
 * `-DBUILD_SHARED_LIBS=ON` is the single most memory requirement lessening option. This toggles LLVM to use as many shared libraries as possible, which means less time will be spent linking **massive** binaries (which *most likely* resulted in your process being killed!). On the flipside, LLVM/Clang will be *somewhat* slower to run (due to using shared libs, the linker can't perform some optimisations).
 * `-DLLVM_USE_LINKER=gold` will use the [`gold` linker](https://en.wikipedia.org/wiki/Gold_(linker)) as opposed to the default GNU `ld`. This also seems to speed up compilation while keeping the memory usage in check.

**Comment by aogrcs** [comment]
Hi, thanks for your compile options, it did work.
My virtual machine has 4G ram, but it still took a long time to build! Hope for an easy way!
Sincerely

**Comment by whisperity** [comment]
4G RAM will most likely won't be enough. It is **definitely** not enough for static linking. We are usually using 16GB machines without virtualisation and even then it takes around an hour to build on slower CPUs.

Unfortunately, Clang is a **huge** system, and their complexity is outside our control. :frowning_face: 

The good thing is that you need to build Clang only once, even if you keep on developing CodeCompass.

(The old `build_deps.sh` could have easily taken around 8 hours to execute, because it built G++, Clang, Java, everything from scratch.)

**Comment by aogrcs** [comment]
It is really huge for using 16G RAM, thanks for your work!
Sincerely

**Comment by aogrcs** [comment]
Hi, I did the set
export CMAKE_PREFIX_PATH=/media/talos/83f370f9-7d30-42c3-85d8-cd2120512c41/clang60_install_dir:$CMAKE_PREFIX_PATH, where the clang60_install_dir containing bin, lib and include etc for clang, but cmake also has error:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)


CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)


-- Boost version: 1.58.0
-- Found ODB: /usr/local/bin/odb   missing components:  pgsql sqlite mysql
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Java: /usr/bin/java (found version "1.8.0.171") 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Adding new plugins:
--   dummy
--   metrics
--   search
--   cpp
CMake Error at plugins/cpp/parser/CMakeLists.txt:1 (find_package):
  Could not find a package configuration file provided by "Clang" with any of
  the following names:

    ClangConfig.cmake
    clang-config.cmake

  Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
  "Clang_DIR" to a directory containing one of the above files.  If "Clang"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!

It did not find the clang60_install_dir? Thanks
Sincerely

**Comment by whisperity** [comment]
The system-installed clang interferes and takes priority over the custom one, it seems.

Please first make sure there is a `bin/llvm-config` under the folder you added to CMake prefix path.

Also, add this `bin` folder (along with the folders where `odb` and `thrift` **binaries** are located) to the `PATH` environment variable too. This way, CMake will find the custom installed Clang's configuration helper tool and find the locations it needs to use.

**Comment by aogrcs** [comment]
Yes, there is a bin/llvm-config exe under the folder /media/talos/83f370f9-7d30-42c3-85d8-cd2120512c41/clang60_install_dir, I also add
export PATH=/media/talos/83f370f9-7d30-42c3-85d8-cd2120512c41/clang60_install_dir/bin:$PATH and type which llvm-config, it said that:
/media/talos/83f370f9-7d30-42c3-85d8-cd2120512c41/clang60_install_dir/bin/llvm-config
but there is still the same error, thanks!

**Comment by whisperity** [comment]
What does calling that binary say? `bin/llvm-config --cmakedir`'s output should point into the install folder.

LLVM 3.8 is very old. I can't really see the reason for this interference, apart from some variable somewhere got cached and isn't letting go. There are just as many cases I've seen with this error not popping up as I've seen where it *does* pop up... There must have been a logic change down the road and CMake seems to keep picking up the system-wide LLVM.

First things first, delete LLVM 3.8 from the system **completely**: `sudo apt-get purge llvm-3.8* clang-3.8*`. Then, while the custom Clang's install `bin` is in `PATH` and the `CMAKE_PREFIX_PATH` being set as it was, recreate the build folder **completely**. Delete the build folder, and then `mkdir` it anew, and then go inside and execute the generation command for CodeCompass' build dir.
