### ISSUE TITLE
Copy the file after `-l` with name build.json

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodeCompass#28]
The file given after `–l` flag in wrapper script should be copied as `build.json` to the project directory. This is necessary because `CodeCompass codechecker ...` command uses this file too.

**Comment by csordasmarton** [comment]
@bruntib Is this issue still relevant? We didn't have a `-l` flag in the CLI.

**Comment by bruntib** [comment]
In Earhart version CodeChecker plugin used the compilation_database.json, that's why this flie was copied to a recognizable place. So this question will be relevant after reviewing CodeChecker plugin.
Is there any other use case which requires this file? In the future we'll have to consider if it is worth storing compilation actions in the database. This table is some cases can be bigger than the file content table.

**Comment by bruntib** [comment]
CodeCompass used to have a sub command which started a CodeChecker checking session. This will not be the part of CodeCompass, so this issue is not relevant.
