### ISSUE TITLE
Cmake problems when building the master branch 

### ISSUE THREAD

**Issue by Benqy77** [Ericsson/CodeCompass#290]
Hi,
    I used to build codeCompass with [https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md](url) in repo.
I have install ODB & SQLite in Ubuntu 16.04 LTS and set env in this system.
export PATH=<odb_install_dir>/bin:$PATH
I have some confuse about <odb_install_dir> which means the install_dir of sqllite?

but when i run cmake, It will cause a problem like this:
cmake .. \
>   -DCMAKE_INSTALL_PREFIX=/ezyuxbe/CodeCompass-install\
>   -DDATABASE=sqlite\
>   -DCMAKE_BUILD_TYPE=Debug

error:
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   log
--   program_options
--   regex
--   system
--   thread
--   log_setup
--   date_time
--   chrono
--   atomic
1. -- Could NOT find ODB (missing:  ODB_EXECUTABLE ODB_LIBODB_FOUND)

--Found Thrift version 0.11.0: /repo/thrift/bin/thrift
-- Found Java: /usr/bin/java (found version "1.8.0.181") 
-- Found GTest: /repo/gtest/lib/libgtest.a

Could you give me some advise?

**Comment by whisperity** [comment]
ODB install dir is where you installed ODB in the earlier part of setting up the dependencies: https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md#odb

This part contains lines like `./configure --prefix=<odb_install_dir>`. ODB is made up of 3 (or 4 if you want to use both database backends) components which are installed under the same prefix (logical "root" folder).

**Comment by Benqy77** [comment]
Thanks a lot,I got it.

**Comment by vitalik-rnd** [comment]
> ODB install dir is where you installed ODB in the earlier part of setting up the dependencies: https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md#odb
> 
Hi, could you please explain what is <odb_install_dir> ? Isn't it the directory where libodb-2.4.0.tar.gz has been unpacked?
I am asking because I am unable to run CodeCompass with SQLite. I have not tested it yet with PostgreSQL.
After successful compilations I am getting the following error message when trying to parse a project:
[ERROR] Couldn't connect to database. Check the connection string.

I have used your example to run the parser:
`keepalive CodeCompass_parser \
  -d "sqlite:database=~/cc/mydatabase.sqlite" \
  -w ~/cc/workdir \
  -n myproject \
  -i ~/myproject/compile_commands.json \
  -i ~/myproject \
  -j 4`

How I can check that SQLite actually works?
Thank you

**Comment by mcserep** [comment]
When using CodeCompass with SQLite, you must define the database path as an absolute path, the tilde (~) for the home directory is not supported.

**Comment by bruntib** [comment]
An extra info: the ODB library can be installed from the official Ubuntu package repository, so it is no more necessary to build it for yourself if you use Ubuntu.

**Comment by vitalik-rnd** [comment]
> When using CodeCompass with SQLite, you must define the database path as an absolute path, the tilde (~) for the home directory is not supported.

Thank you for this info. It solved the issue in the parsing stage.
It seems that parsing stage ended successfully.
But when I try to start the service using:
`keepalive CodeCompass_webserver \
  -w ~/cc/workdir \
  -p 6251 \
  -d "sqlite"`
or with:
`keepalive CodeCompass_webserver \
  -w /home/cc/cc/workdir \
  -p 6251 \
  -d "sqlite"`
I am getting the following error message (in loop):
`[ERROR] Wrong connection string: 'sqlite;database=/home/cc/cc/mydatabase.sqlite' for project: 'life' for service: 'GitService'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Wrong database!`
Any ideas?
Thanks

**Comment by vitalik-rnd** [comment]
> Hi,
> 
> The <odb_install_dir> is the path where you installed odb lib after its compilation with "make install". This install directory can be given with --prefix flag at the configure command as the documentation describes. However, this path is needed for compiling CodeCompass itself. Currently you're having a runtime issue. How did you compile CodeCompass? Make sure that you provided -DDATABASE=sqlite flag at the corresponding cmake command.


> An extra info: the ODB library can be installed from the official Ubuntu package repository, so it is no more necessary to build it for yourself if you use Ubuntu.

Thank you for this information.
@mcserep's comment helped to pass that stage.
Could you please consider adding that note to the user's guide?

**Comment by bruntib** [comment]
There is a small mistake in the connection string: the database engine in the beginning should be separated by a colon character, and the following parameters are separated by a semicolon: `sqlite:database=db_name;port=12345;host=localhost`. A more verbose error message would really be helpful. We'll improve it.

**Comment by vitalik-rnd** [comment]
Hi, I have updated the connection string to `sqlite:database=/home/cc/cc/mydatabase.sqlite` and ran the server with:
`./keepalive ./CodeCompass_webserver \
  -w /home/cc/cc/workdir \
  -p 6251 \
  -d "sqlite:database=/home/cc/cc/mydatabase.sqlite"`

During the startup, I got the following message:
`[INFO] Start serving search for index /home/cc/cc/workdir/life/search
[ERROR] Getting repository head failed: -9
./keepalive: line 18:  1103 Segmentation fault      (core dumped) $@`

Doing first commit in git fixed the issue (before that I just did `git init`).

Next, the server loaded but with error messages:
`[SEVERE] Failed to load the file name suggestion database!
java.io.EOFException
	at org.apache.lucene.store.InputStreamDataInput.readByte(InputStreamDataInput.java:37)
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:96)
	at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:134)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:322)
	at org.apache.lucene.util.fst.FST.<init>(FST.java:308)
	at org.apache.lucene.search.suggest.analyzing.AnalyzingSuggester.load(AnalyzingSuggester.java:593)
	at cc.search.suggestion.SuggestionHandler.loadFileNameSuggester(SuggestionHandler.java:120)
	at cc.search.suggestion.SuggestionHandler.loadDatabases(SuggestionHandler.java:47)
	at cc.search.service.app.service.SearchHandler.<init>(SearchHandler.java:156)
	at cc.search.service.app.service.ServiceApp.<init>(ServiceApp.java:30)
	at cc.search.service.app.service.ServiceApp.main(ServiceApp.java:51)`

First I tried to use Firefox to open the web page. Firefox tab crashed.
After that I checked with Chrome and it loaded the page.
In Chrome developer tools I saw the following error messages:

`GET http://localhost:6251/scripts/node_modules/jquery.fancytree/lib/jquery-ui.custom.js net::ERR_ABORTED 404 (Not Found)
jquery.min.js:2 Uncaught Error: Fancytree assertion failed: Fancytree requires jQuery UI (http://jqueryui.com)
    at Function.error (jquery.min.js:2)
    at t (jquery.fancytree-all.min.js:33)
    at jquery.fancytree-all.min.js:33
    at jquery.fancytree-all.min.js:33
    at jquery.fancytree-all.min.js:33
    at jquery.fancytree-all.min.js:29
    at jquery.fancytree-all.min.js:31
error @ jquery.min.js:2
t @ jquery.fancytree-all.min.js:33
(anonymous) @ jquery.fancytree-all.min.js:33
(anonymous) @ jquery.fancytree-all.min.js:33
(anonymous) @ jquery.fancytree-all.min.js:33
(anonymous) @ jquery.fancytree-all.min.js:29
(anonymous) @ jquery.fancytree-all.min.js:31
(index):50 GET http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/src/jquery.fancytree.table.js net::ERR_ABORTED 404 (Not Found)
thrift.js:348 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
flush @ thrift.js:348
WorkspaceServiceClient.send_getWorkspaces @ VM2796 WorkspaceService.js:144
WorkspaceServiceClient.getWorkspaces @ VM2796 WorkspaceService.js:121
(anonymous) @ model.js?1544613899580:54
runFactory @ dojo.js:1175
execModule @ dojo.js:1303
execModule @ dojo.js:1294
(anonymous) @ dojo.js:1341
...
...`

I have opened one of the analyzed files using the File Manager
The file has been displayed but marked with red "(Not parsed)" message.
Other files also had "(Not parsed)" message.

When I right-click on the file, nothing happened. I am unable to see the popup menu like in your demo.
On each right-click I can see in Chrome developer tools the following message:
`Text.js?1544613899580:433 Uncaught TypeError: Cannot read property 'id' of undefined
    at Object._markUsages (Text.js?1544613899580:433)
    at Object._eventHandler (Text.js?1544613899580:408)
    at Text.js?1544613899580:256
    at signal (codemirror.js:1165)
    at signalDOMEvent (codemirror.js:1174)
    at CodeMirror.onMouseDown (codemirror.js:7271)
    at HTMLDivElement.<anonymous> (codemirror.js:3906)`

Textual search worked for me, I have searched for "world" and got results.

Any idea what to do next to make it work just like in your demo? :)

Thank you very much for your help
