### ISSUE TITLE
Build error no matching function for call to.

### ISSUE THREAD

**Issue by Benzy77** [Ericsson/CodeCompass#292]
Build error:
**/ezyuxbe/CodeCompass/webserver/include/webserver/thrifthandler.h:132:7: error: no matching function for call to** ‘cc::webserver::ThriftHandler<cc::service::dummy::DummyServiceProcessor>::LoggingProcessor::process(boost::shared_ptr<apache::thrift::protocol::TProtocol>&, boost::shared_ptr<apache::thrift::protocol::TProtocol>&, cc::webserver::ThriftHandler<cc::service::dummy::DummyServiceProcessor>::CallContext*)’
       _processor.process(inputProtocol, outputProtocol, &ctx);

    I have check code in thrifthandler.h 132:7.  May be my environment has some errores configure in 
    export CMAKE_PREFIX_PATH=<thrift_install_dir>:$CMAKE_PREFIX_PATH ?
    Could you give me some advise?

    configure information:
-- Found the following Boost libraries:
--   filesystem
--   log
--   program_options
--   regex
--   system
--   thread
--   log_setup
--   date_time
--   chrono
--   atomic
-- Found ODB: /repo/odb/bin/odb  found components:  pgsql sqlite
**-- Found Thrift version 0.11.0: /repo/thrift/bin/thrift**
-- Found Java: /usr/bin/java (found version "1.8.0.181")
-- Found GTest: /repo/gtest/lib/libgtest.a
-- Adding new plugins:
--   dummy
--   git
--   cpp
--   cpp_reparse
--   metrics
--   search
-- Configuring done
-- Generating done
-- Build files have been written to: /ezyuxbe/CodeCompass/build

**Comment by whisperity** [comment]
Your Thrift seems to be too new! The dependency guide says **0.10.0** version, not 0.**11**

**Comment by whisperity** [comment]
Your Thrift is 0.11.0 version. The dependency documentation says 0.**10**.0 is to be used.

**Comment by Benqy77** [comment]
Thanks whisperity.

**1 It has built successfully in my environment,when i just use "make" command.
Scanning dependencies of target ldlogger**
[100%] Linking C shared library libldlogger.so
**[100%] Built target ldlogger**
Installation of npm packages are finished.
-- Installing: /ezyuxbe/CodeCompass-install/share/codecompass/webgui/userguide/header.html
-- Installing: /ezyuxbe/CodeCompass-install/share/codecompass/webgui/userguide/footer.html
-- Installing: /ezyuxbe/CodeCompass-install/share/codecompass/webgui/userguide/Doxyfile
Install userguide...
Install userguide has been finished.

**2 But when I use "make -j 2" command,it will course other qustion. It let me confuse. if you know reason could you tell me why?** 
Scanning dependencies of target dummythrift
[ 14%] Building CXX object plugins/dummy/service/CMakeFiles/dummythrift.dir/gen-cpp/dummy_constants.cpp.o
In file included from /ezyuxbe/CodeCompass/plugins/dummy/service/gen-cpp/dummy_constants.h:10:0,
                 from /ezyuxbe/CodeCompass/plugins/dummy/service/gen-cpp/dummy_constants.cpp:7:
**/ezyuxbe/CodeCompass/plugins/dummy/service/gen-cpp/dummy_types.h:18:27: fatal error:** thrift/stdcxx.h: No such file or directory
compilation terminated.

**3 This is my env configure.**

> export GTEST_ROOT=/repo/gtest
> export CMAKE_PREFIX_PATH=/repo/thrift:$CMAKE_PREFIX_PATH
> export CMAKE_PREFIX_PATH=/repo/llvmbuildinstall/:$CMAKE_PREFIX_PATH
> **export CMAKE_PREFIX_PATH=/repo/odb:$CMAKE_PREFIX_PATH**
> export PATH=/repo/thrift/bin:$PATH
> **export PATH=/repo/odb/bin:$PATH**

Threr are some confuses in configure.  export PATH=<odb_install_dir>/bin:$PATH
Wheather ODB PATH is just mean ODB compiler which is the tag named **Ubuntu 16.04 LTS** in deps.md rather than https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md#odb ?

**Comment by whisperity** [comment]
ODB Path is **all** of ODB as the guide uses this variable for every ODB-related thing's install location.

Unfortunately these environment-related issues are very hard to debug remotely.

Please make sure you removed the previous higher version of Thrift completely from the "repo location" you are using before installing the required one. And then do a completely new build (also delete the build folder of CodeCompass and make it from scratch).

**Comment by Benqy77** [comment]
Thank a lot.

**Comment by Benqy77** [comment]
Thanks a lot.
