### ISSUE TITLE
Remove extra dynamic memory allocations in Graph::dotToSvg()

### ISSUE THREAD

**Issue by elfring** [Ericsson/CodeCompass#321]
I find [the usage of the new operator questionable for the variables “result” and “length” in the implementation of the function “Graph::dotToSvg”](https://github.com/Ericsson/CodeCompass/blob/a45aaeb300e7739980a8c1814eff65cc477052f6/util/src/graph.cpp#L22 "Update candidate").
Can it be a bit more efficient without these dynamic memory allocations?

**Comment by mcserep** [comment]
Memory allocation on the stack is indeed faster compared to the heap, and could be applied here. On the other hand I consider this optimization minor, since the `Graph::dotToSvg` method is not called frequently, only once per diagram request.
Note: `Graph::dotToSvg` is unused, but the same observation can be made for `Graph::output`.

Feel free to make a pull request.
