### ISSUE TITLE
Reduce supported Ubuntu versions

### ISSUE THREAD

**Issue by filbeofITK** [Ericsson/CodeCompass#400]
There was a lot going around with this odb break and the arrival of Ubuntu Focal Fossa, and as far as I can see, supporting 3 versions slows down the development process. The increasing difference between the dependencies and boundaries of each version, make every idea harder to execute.

It also affects the testing of one's commits or branches, because we have to test the program against all of the versions. Which takes time, and each developer has to have all 3 OS-es at hand just for testing. Of course this doesn't apply to all types of changes but to a significant amount of them. 

That is why I propose to give up support for one version.

**Comment by whisperity** [comment]
There's already an ongoing  discussion about this in #393.

In short: 16.04 will go out of support soon (around half year from now) globally anyways. We can't drop support for 18.04 for the foreseeable future due to company internal reasons mostly.

**Comment by mcserep** [comment]
I agree. Unless we face a major complication in the future with Ubuntu 16.04, we shall support it until its lifetime period (April 2021). Most issues (currently) are with 18.04, but we cannot drop development environment support for that, as @whisperity described.

**Comment by whisperity** [comment]
As for testing changes in other configurations, it should be the CI's responsibility. With LLVM, we're developing against even proprietary operating systems that we do not have access to, and the test jobs take care of it (more or less).

To drive this, the amount of work in the CI jobs need to be lessened (i.e. 3rdparty stuff should not be rebuilt all the time!), but for that I think the surefire way is a new repo, but creating a repo under this org is not something we can locally do easily.

If the tests need 5 min to run on average, it's not unreasonable to expect people to check the CI after pushing their PR, or the next morning. And because we can pre-check *before* merging, we're better off than LLVM too, where you have to push to master first, and then realise overnight you broke the world for the US-timezone people.

**Comment by mcserep** [comment]
> If the tests need 5 min to run on average, it's not unreasonable to expect people to check the CI after pushing their PR, or the next morning. 

Travis sends an email to the committer if the CI pipeline fails, so it is not easy to miss if you broke the pipeline :)

**Comment by whisperity** [comment]
> > If the tests need 5 min to run on average, it's not unreasonable to expect people to check the CI after pushing their PR, or the next morning.
> 
> Travis sends an email to the committer if the CI pipeline fails, so it is not easy to miss if you broke the pipeline :)

I don't think it happens for pull requests before merge though. When I was making #393 I didn't get any emails whatsoever.
