### ISSUE TITLE
Incremental parsing segfaults on libgit2

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#430]
When incremental parsing is executed on libgit2 on the server behind codecompass.net, building the project is successful, however, after a few TUs, parsing fails with the error message "LLVM error: out of memory". The error is thrown during the cleanup phase.

**Comment by mcserep** [comment]
Please provide further information on this bug:
- specify at which point of the parsing the error occurs (maybe also provide console dump);
- can the error be reproduced on your local computer?

**Comment by intjftw** [comment]
Answer to reproducing: it did not emerge on my computer so far.

**Comment by whisperity** [comment]
`LLVM Error:` is an unfortunate side-effect of depending on LLVM, which as a hot-headed bull registers itself as the global terminate handler... The issue is possible to not have come from LLVM. It says `Out of memory` when an `std::bad_alloc` is thrown. (For example, when developing #386 and trying buffer overflow attacks, I was also getting `LLVM Error: Out of memory` aborts until I have manually deleted the reparse plugin (which uses LLVM on the server side...) from the build.)

The actual output pops from here:

https://github.com/llvm/llvm-project/blob/llvmorg-7.0.0/llvm/lib/Support/ErrorHandling.cpp#L169-L174

I think you might have to either play with `ulimit`, or [Linux Control Groups](https://wiki.archlinux.org/index.php/cgroups) or just simply by manually tinkering the available memory of a virtual machine to get the error to pop out.

**Comment by intjftw** [comment]
Resolved in #493.
