### ISSUE TITLE
New parser plugins

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#465]
Aside from bugfixes, we should enrich CodeCompass with new parser plugins. I realize that takes a lot of work and refactoring on the present code, but to make CodeCompass more popular and widespread, we should seriously consider this. We already have the Python parser which is under integration, we can also port the Java parser from Earhart, and there is the rudimentary version of the Haskell parser.
I think the right direction is to develop parsers for the currently popular programming languages, such as C# or JavaScript. We could use GitHub data or public lists, such as [PYPL](http://pypl.github.io/PYPL.html) or [TIOBE](https://www.tiobe.com/tiobe-index/) to determine which languages are worth the effort.
I believe we could get students from the software technology lab to work on these projects, as they would be a lot of work.

**Comment by bruntib** [comment]
Yes, this would be really important to support languages other than C/C++. I would suggest creating a branch for a language plugin. Since it really is a huge work developing a language plugin, it could be more feasible assigning multiple students on the development of one specific language that we choose for them taking their preference into consideration. They are committing to the new branch and these commits also go through a review process.

If some feature is committed to master branch, it means that we need to support it "officially". So I think we should establish some measurable scale that determines what's "good enough" to be the part of master branch. Coverage of `language.thrift` could be the part of this scale.

Maybe we could start with Python parser, since @rmfcnb is already working on it. He has some prototype implementation.

**Comment by bruntib** [comment]
Oh, and as you mentioned, we don't forget about Haskell parser which is half-done.

**Comment by zporky** [comment]
Next should be Java. We had a few earlier attempts, some were quite
successful.

gsd

bruntib <notifications@github.com> ezt írta (időpont: 2020. szept. 4., P,
20:09):
