### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by filbeofITK** [Ericsson/CodeCompass#488]
I've been using the modelcpp/codecompass:dev image quite much nowadays and I got the feeling that I'm not using a container that was built to help the developer,  it is rather a base image, since it does not contain any developer tools. So that got me thinking that the current dev image should be renamed to something like codecompass:base (or anything like that).

The new dev image should be able to run multiple Ubuntu versions, and contain dev tools like git, midnight-commander, ranger.....The list is as long as we want it to be. 
With these changes the layout of the Docker images wouldn't turn over, the runtimes could originate from the base image with the multi-stage build, just as they do now, but we would also have great developer tool, with which we could test our code against all the supported OS versions.
Naturally this dev image wouldn't be uploaded to the dockerhub, since it's size would be huge because of all the integrated tools. It would only be part of the code on github and everyone would build it with the OS version they desire to test against.

**Comment by mcserep** [comment]
The `dev` image contains the libraries required to **build** CodeCompass. Which is required when developing CodeCompass, hence the the name `dev`. The `runtime` images only contains the dependencies required to **run** CodeCompass. (The `web` images are the same, but only for running the webserver.)

**The `dev` image shall not contain developer tools.**
The purpose of this image (beside being a base image for the `runtime` images as you have correctly observed) is to contain the dependencies of CodeCompass. The workflow is the following (as described [here](https://github.com/Ericsson/CodeCompass/blob/master/docker/README.md)):
 - the developer has the preferred developer tools on his/her host computer installed, working on the preferred OS;
 - the dependencies and tools to build CodeCompass are contained in a running docker container of the `dev` image;
 - the source code of CodeCompass is shared between the docker container and the host computer through a docker volume.

Thus the developer can develop CodeCompass with his/her preferred tools (edit the source code), but do not need to compile & install the dependencies of CodeCompass and CodeCompass itself is built inside the docker container. This speeds up development on a new environment; and makes development possible on a not-supported OS.
This is the standard concept of a dockerized development environment.

Since each developer could have various preferred developer tools, it would be unmaintainable to contain all of them in a docker image, so everyone could be satisfied. Also, this would mean that if a developer works on multiple projects (with a dockerized development environment support), he/she would have multiple instances of all those developer tools, which would be a huge waste of resources, especially disk space.

**Comment by filbeofITK** [comment]
I understand that you feel there is no need to integrate more tools to the docker image, but even so the multi OS testing enviroment would be crucial for testing. Also I don't really fell like consuming even a few gigabytes is a big deal with the capacities of the current computers.

**Comment by mcserep** [comment]
Creating development docker images for other officially supported OSes to support multi OS testing is a valid a enhancement. We could tag them like e.g. `dev-ubuntu2004` and `dev-ubuntu1804`.
