### ISSUE TITLE
Migrate CI from Travis to another CI engine

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#494]
Applicable since November 2, Travis CI basically [dropped free support towards public, open-source projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

According to their announcement, they _"have encountered significant abuse of the intention of this offering (increased activity of cryptocurrency miners, TOR nodes operators etc.)"_. Their new pricing model for public, open-source projects is the following:

> [...] those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> - When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
> - **We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.**
> How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount).

On my own CodeCompass fork I have done 7 CI jobs for CodeCompass since November 2 and have already used up 2150 credits of the given 10000. I don't know whose credits are we using in this Ericsson repository, but it will quickly get depleted. So unless Ericsson is willing to pay for Travis CI; or we are planning to basically beg to the Travis Support Teams regularly for new free credits since CodeCompass is open-source (which would be ridiculous in my opinion), we must drop the usage of Travis.

Alternative free CI solutions to consider:
 - GitHub Actions. The [GitHub-hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners) use Azure Cloud and have 2 CPU cores, 7GB RAM and 14GB SSD. The storage space will most likely not be enough though.
 - GitLab CI on GitLab.com. The [shared runners](https://docs.gitlab.com/ee/user/gitlab_com/#linux-shared-runners) use Google Cloud and have 1 CPU core, 3.75GB RAM, 25GB HDD.
- GitHub Actions with [self hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners). In this case we need to set up a server.
- GitLab CI on a self-hosted instance. We have the infrastructure ready at ELTE.
- Another free solution, e.g. [AppVeyor](https://www.appveyor.com/), which could be examined.

As a comparison: Travis mostly used AWS and a [single job had](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) 2 CPU cores, 7.GB RAM and ~50GB storage space.

**Comment by whisperity** [comment]
> On my own CodeCompass fork I have done 7 CI jobs for CodeCompass since November 2 and have already used up 2150 credits of the given 10000. I don't know whose credits are we using in this Ericsson repository, but it will quickly get depleted.

If you are using CI minutes on your own fork, it is counted against the allotment of your account, so in this case, `@mcserep`. Every started minute of virtual machine execution on Linux costs 10 credits. macOS and Windows machines cost more... much more.
The repository owner pays for the usage of that repository. AKA, If I want to f*ck you over, I could send a BUNCH of pull requests that are only aimed at running as slow as possible and thus manage to gut your fork and your account's allotment...

GitLab's SaaS CI with the "shared runners" are also time-limited. But unlike Travis (where once your free 10k credits run out, you're basically SOL until you pay), GitLab, *for now at least*, offers 2000 minutes (so double Travis' amount), but that's a *monthly* quota. However, considering they are only `-j1`, I would say at the end of the day, it balances out similarly to Travis, given half the CPU and RAM capacity... From [Changes to CI pipeline minutes for new free users (Mar 18, 2020)](https://about.gitlab.com/releases/2020/03/18/ci-minutes-for-free-users/):

> Moving forward, all free accounts will have 2000 pipeline minutes per group per month independent of the visibility of the project. 

GitHub Actions are, as of now, free and unlimited for *public* repositories (while free tier accounts get 2k minutes per month for their private repositories)

> So unless Ericsson is willing to pay for Travis CI

A year or two ago (as we used to regularly CI CodeChecker for OS/X...) this came up, considering that the Mac jobs were always piling up (because Travis couldn't just spin up OS/X executors in virtual images...). Let's just say that the politically correct phrasing is that it is *highly* unlikely to happen... *especially* for CodeCompass. We did not manage to make it (a paid tier account) happen for CodeChecker. In the end, [OS/X tests were just... dropped](http://github.com/Ericsson/codechecker/pull/3003).

What we *could* have, from the corporate standpoint, is some machines in-house that run the CI, but... those machines would not be accessible from the public PoV. And I do not think you could easily set GitHub up in a way that even the logs of the CI run are sent back to GitHub to be shown publicly with the repository (I think you can achieve similar with GitLab, though -- there are a few students on this semester's Project Tools course who are running their own C#-based CI with a GitLab runner in Azure for their C# based project -- and the logs neatly appear alongside the repository).

> basically beg to the Travis Support Teams regularly for new free credits since CodeCompass is open-source (which would be ridiculous in my opinion), we must drop the usage of Travis.

In case of Travis, 69$ (noice.) will get the repo owner 1 concurrent job (which is really slim) but at least, if I read it correctly, *without* the credits/run time madness, according to [the docs](http://docs.travis-ci.com/user/billing-overview/#travis-ci-plan-types). So you either pay-as-you-go, 15$ per 25k credit (so 2.5k minutes Linux build time), or you cough up the lump sum for the amount of concurrency you want, and not look back.

So far, it seems that the GitHub Student Developer Pack (or however it is called in this season...) is connected to Travis as the lowest tier (69$) 1-concurrent-job plan, without the credit yadda, see image. However, this is definitely not a panacea in the long run... especially that right now the repository is owned by an organisation, which cannot be a student.
![travis-ci.com settings page showing `EDUCATION` subscription being on the "1 concurrent job" plan](https://user-images.githubusercontent.com/1969470/99917954-15024c00-2d14-11eb-9b47-fc3f7555da5e.png)

**Going and begging is ridiculous, I agree.**

Personally, I think all these changes will only help in entrenching GitHub's monopoly more (to which in the end they can just decide to make users pay, too...), or the world will slowly revert back to "Who the fuck cares about testing?" and we'll just have worse quality software. Just another nail in the coffin.

(Google Photos storage is also becoming non-free in roughly half a year from now on.)

I have yeeted the Travis integration off of my account and disabled all remnants of it across my own projects.

**Comment by mcserep** [comment]
Well, it has happened eventually, CI builds are not running for *Ericsson/CodeCompass* now on Travis.

![Screenshot from 2020-12-02 17-41-24](https://user-images.githubusercontent.com/7405458/100902983-b1231480-34c5-11eb-947c-fc9a5ba47992.png)

**Comment by whisperity** [comment]
There is a new announcement: https://blog.travis-ci.com/oss-announcement

> Open source has always been and always will be at the core of what Travis CI stands for, reflected in the fact that we’re still committed to offering accounts specifically for open source repositories.
> [...]
> We’re confident that our recent changes have brought the abuse of open source at Travis CI under control, ensuring resources are available to all developers and teams as well as improvements to the overall performance and stability of the platform.

Yeah, the abuse is contained because people are flocking away...

And yes, the credits ran out for the entire @Ericsson organisation:

![image](https://user-images.githubusercontent.com/1969470/101018326-a15e0b80-356b-11eb-8771-8960a35ab52b.png)

**Comment by mcserep** [comment]
> Yeah, the abuse is contained because people are flocking away...

Their attitude is just hilarious ...

> And yes, the credits ran out for the entire @Ericsson organisation:
> 
> ![image](https://user-images.githubusercontent.com/1969470/101018326-a15e0b80-356b-11eb-8771-8960a35ab52b.png)

Thanks for confirming this.

The best alternative seems to be GitHub Actions, @intjftw applied to examine whether this is possible or not. (Low disk quota can be an issue.)

**Comment by whisperity** [comment]
The rabbit hole goes deeper. (via http://twitter.com/james_hilliard/status/1336081776691843072):

> At the moment, credit allocation for OSS projects is on hold as per directives from management.

This was the official reply a repo owner got from Travis when they pleaded.
