### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#521]
It is a frequently re-emerging topic when CodeCompass is presented to a team if there is an option for LDAP-based authentication. We should upgrade the current authentication to use LDAP.

**Comment by mcserep** [comment]
Shouldn't be too hard to implement if we can use an LDAP library and do not need to implement it.
The [ldap.com](https://ldap.com/client-apis/) site recommends the old [ldap-cpp](https://code.google.com/archive/p/ldap-cpp/wikis/PageName.wiki) wrapper of the OpenLDAP library (written in C). While it has not been updated quite a long time, it can work for us, as we would only need the most basic feature set of LDAP (authentication).
Here is an export of that library on GitHub: https://github.com/jubalskaggs/ldap-cpp (since Google Code was archived).

**Comment by mcserep** [comment]
Another approach is to use the continuously developed [OpenLDAP](https://www.openldap.org/), although it has a C API.
It is still not that hard, I have a PHP implementation for LDAP-based authentication on the link below, and PHP just uses the C API, so this gist can serve as a starting point:
https://gist.github.com/mcserep/65db3c6e507a16c58458d6c14ea57e09
