### ISSUE TITLE
How to enable javaparser? 

### ISSUE THREAD

**Issue by kyle-ingka** [Ericsson/CodeCompass#552]
I used CodeCompass_parser to parse a java project. 

However, the web server UI shows NotParsed for all java files. 
![image](https://user-images.githubusercontent.com/74636923/149971485-a25d87c2-59aa-44bd-ab49-c0699422bf02.png)

Read the doc but find nothing related.

**Comment by intjftw** [comment]
The Java plugin is currently under development. It is in an advanced state, and hopefully will be merged in a short period of time. Meanwhile, you can try it by checking out the `release/java_plugin` branch. It works the same way as the C/C++ plugin, needs a source directory, or a jar file. In order to use it by providing a jar as an input, you will need an additional dependency, `unzip`, which can be installed from `apt` in Ubuntu.

**Comment by kyle-ingka** [comment]
Thanks for the reply and effort on the challenging work. 

I will tinker with the candidate branch, while waiting for the release.
