### ISSUE TITLE
Clicking any node inside a lambda does not work

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#583]
If you click on a node inside a lambda expression, the lambda declaration will be highlighted and marked (showing the lambda in the info tree) instead of the node itself. See the image for an example with `getFile` clicked.
![Screenshot from 2022-10-03 11-58-18](https://user-images.githubusercontent.com/26124787/193550695-cb942174-d8e1-4de1-b2d7-e1c76a5db495.png)

**Comment by dbukki** [comment]
I found that the issue is with the fact that since commit 3bc3c7f1f69c4a1a0680dc289b50d835d7cf74a1, implicitness is hereditary for child nodes during traversal via the _isImplicit member variable. I guess the original assumption was that once a node is implicit, everything in it must surely also be implicit. But this is simply not the case with lambdas: While the closure type itself is in fact implicit, its operator() is not, and yet it is treated as such. This marks everything inside a lambda point to unspecified locations, because _fileLocUtil.setRange is never called for any of its child nodes.
