### ISSUE TITLE
invalid byte sequence for encoding "UTF8" and crash

### ISSUE THREAD

**Issue by smallSwed** [Ericsson/CodeCompass#620]
I have problem parsing our project with `CodeCompass_parser`

#### Error:
```shell
2023-08-01 19:12:17 [INFO] (26/574) Parsing /home/vboxuser/Source/Core/RequestStruct.cpp
terminate called after throwing an instance of 'odb::pgsql::database_exception'
  what():  22021: ERROR:  invalid byte sequence for encoding "UTF8": 0x96
Aborted (core dumped)
```

#### Call from terminal inside the source directory
```shell
CodeCompass_parser -d "pgsql:host=localhost;port=5432;user=compass;password=<pass>;database=sdkdb" -w ~/workdir -n sdk -i . -i ../bin/core/compile_commands.json -j 4
```
----
My system is a virtual machine:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Comment by smallSwed** [comment]
After searching the postgresql logs I found the problematic operation:
```
2023-08-08 18:49:31.538 EEST [24947] compass@opc_ua_sdk ERROR:  invalid byte sequence for encoding "UTF8": 0x96
2023-08-08 18:49:31.538 EEST [24947] compass@opc_ua_sdk STATEMENT:  INSERT INTO "FileContent" ("hash", "content") VALUES ($1, $2)
```
So the problem is the file content not being UTF-8 encoded. I converted the problematic files in the project to UTF-8 (from UTF16)
but now there is a second problem with some database operation:
```
2023-08-09 09:37:14.799 EEST [2557] compass@opc_ua_sdk ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2023-08-09 09:37:14.799 EEST [2557] compass@opc_ua_sdk STATEMENT:  INSERT INTO "CppDocComment" ("id", "contentHash", "content", "entityHash") VALUES (DEFAULT, $1, $2, $3) RETURNING "id"
```
In this case I am not sure which of the fields is the problematic. 
According to this: [https://stackoverflow.com/questions/1347646](https://stackoverflow.com/questions/1347646/postgres-error-on-insert-error-invalid-byte-sequence-for-encoding-utf8-0x0) the NULL is not supported in postgresql.

**Comment by mcserep** [comment]
Hi @smallSwed,
Thanks for trying out CodeCompass! Based on your last error message you still have incorrect UTF-8 characters in your source files. Zero byte (0x00) should not occur in a text file, as that is the EOF symbol. Since insertion into the `CppDocComment` table fails, most likely an in-code C++ documentation part contains an invalid symbol.

The database tables for CodeCompass are created with the default encoding of the database engine. In case you would like to parse an UTF-16 encoded project, try configuring PostgreSQL to default to that encoding beforehand. Although, I must admit I am not sure any project member ever parsed a non UTF-8 project, and supporting UTF-16 is not on our roadmap, so no guaranties that this will work. (But converting your project to UTF-8 should definitely work if there are no invalid characters anymore.)
